TheEvergreenStateCollege/upper-division-cs

- dsa-23au/SoftwareSetup.md
There's a typo in the documentation, this fixes it.
> dsa-23au/SoftwareSetup.md: fixed incorrect path

- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/ArrayWrapper.java
Adding some changes from last few days. Please review and comment/approve when you have a chance!
> Adding code changes since `notice of a revert` occurred

- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/ArrayWrapper.java
The method we worked on in class.
> Updated ArrayWrapper.remove

- dsa-23au/notes/docs/week-01/2023-09-28-Co-Creation.md
- dsa-23au/notes/docs/week-02/Co-Creation-02.md
> Hyre elson branch

- dsa-23au/java-dsa/arrays-links/src/test/java/dev/codewithfriends/ArrayWrapperTest.java
- dsa-23au/java-dsa/arrays-links/src/test/java/dev/codewithfriends/LinkedListWrapperTest.java
> Elson array links

- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/LinkedListWrapper.java
> Implementing LinkedListWrapper.contains

- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/ArrayWrapper.java
- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/LinkedListWrapper.java
(as it is not relevant to linkedlistwrapper testing)
Added some missing curly brackets
Replaced a faulty size variable with currentSize
> Temporarily Commented out ArrayWrapper

- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/LinkedListWrapper.java
> changed remove method

- dsa-23au/PeriodicTable.md
All data structures and algorithms on them, categorized as CRUD operations
> Initial commit of Periodic Table of DSA

- dsa-23au/java-dsa/weiss-pham-dmv/pom.xml
- dsa-23au/java-dsa/weiss-pham-dmv/src/main/java/dev/codewithfriends/Appointment.java
- dsa-23au/java-dsa/weiss-pham-dmv/src/main/java/dev/codewithfriends/Clerk.java
- dsa-23au/java-dsa/weiss-pham-dmv/src/main/java/dev/codewithfriends/DMVMain.java
- dsa-23au/java-dsa/weiss-pham-dmv/src/main/java/dev/codewithfriends/Driver.java
- dsa-23au/java-dsa/weiss-pham-dmv/src/test/java/dev/codewithfriends/AppTest.java
Build on this example to complete the DMV example for Week 4 homework.
> Starter DMV project.

- dsa-23au/java-dsa/weiss-pham-dmv/src/main/java/dev/codewithfriends/Driver.java
So as a whole it runs but with a couple of errors that aren't very obvious on how to fix. Here is the message.
Running] cd "/workspace/upper-division-cs/dsa-23au/java-dsa/weiss-pham-dmv/src/main/java/dev/codewithfriends/" && javac Driver.java && java Driver Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
Driver.java:34: error: cannot find symbol
public boolean isLateForAppointment(Appointment appointment) {
^
symbol:   class Appointment
location: class Driver
1 error
> Update Driver.java whereismyprozac

- dsa-23au/notes/docs/week-04/Projects.md
Starter Maven project for DMV exercise as part of Homework 4.
Teams should continue working on it this week.
Add markdown notes of final project from class on Tuesday, October 17.
> Begin final project summary and guidance.

- dsa-23au/java-dsa/heaps-trees/src/main/java/dev/codewithfriends/BinaryNode.java
- dsa-23au/java-dsa/heaps-trees/src/main/java/dev/codewithfriends/BinarySearchTree.java
in class assignment to create a binary search tree
> Binary Search tree

- dsa-23au/java-dsa/heaps-trees/src/main/BinarySearchTree.java
- dsa-23au/java-dsa/heaps-trees/src/main/java/dev/codewithfriends/BinaryNode.java
> Start BST.

- dsa-23au/java-dsa/pswish-natmcl/pswish-app/pom.xml
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/Car.java
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/DataSet_DSAau_pswish.csv
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/Driver.java
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/HighwayTune.java
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/test/java/com/pswishcorp/app/AppTest.java
Apache 1.7 no longer supported, changed to 1.8 in pom.xml
Added some code for final project work.
Current final data structure on the docket: Map of hash maps or python(dictofdicts).
Created new mvn project
`mvn package` and `mvn test` passes.
> Updated apache to 1.8 after build error, more code construction v.04

- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/Time_Driving_Spreadsheet.csv
This is my spreadsheet for my time spent driving to and from The Evergreen State College.
I choose to remodel my spreadsheet so our data tables would be similar.
> Nathan's driving log

- dsa-23au/java-dsa/DawsonWhi-app/README.md
- dsa-23au/java-dsa/DawsonWhi-app/pom.xml
- dsa-23au/java-dsa/DawsonWhi-app/src/main/java/com/mycompany/app/App.java
- dsa-23au/java-dsa/DawsonWhi-app/src/test/java/com/mycompany/app/AppTest.java
> added test App and README.md

- dsa-23au/PeriodicTable.md
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/Buffer.java
- dsa-23au/java-dsa/pswish-natmcl/pswish-app/src/main/java/com/pswishcorp/app/Driver.java
1. Why is this change being made? Project work continues
2. What has changed? Added a class to run independently for now. 
3. How was this tested? Command line output
4. Anything else to discus? Not at this time
5. Any other documentation? Not at this time
> Final project work, v0.5

- dsa-23au/java-dsa/heaps-trees/README.md
- dsa-23au/java-dsa/heaps-trees/src/main/java/dev/codewithfriends/BSTMain.java
> Finally compiled the Dfs Diagram

- dsa-23au/java-dsa/Torsten/pom.xml
- dsa-23au/java-dsa/Torsten/src/main/java/com/ActivityTor/app/App.java
- dsa-23au/java-dsa/Torsten/src/test/java/com/ActivityTor/app/AppTest.java
Beginning package for my project
> Tors Project

- dsa-23au/java-dsa/NMac-app/pom.xml
- dsa-23au/java-dsa/NMac-app/src/main/java/com/nathanMcL/app/App.java
- dsa-23au/java-dsa/NMac-app/src/test/java/com/nathanMcL/app/AppTest.java
Created the Maven project files. I wrote down the steps. I will still need practice. What I was doing wrong was I was in the wrong directory trying to create the MVN project. I was not doing the steps to merge and commit the MVN file correctly as well.
> Created Maven NMac-app

- dsa-23au/java-dsa/sorting/pom.xml
- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/App.java
- dsa-23au/java-dsa/sorting/src/test/java/dev/codewithfriends/AppTest.java
Created the Insertion sort java class we worked on in class
> added InsertionSort

- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/App.java
> start merge sort -hmh

- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/App.java
implemented temporary array to merge left and right into
> Dylana sort

- dsa-23au/DSAFormat.md
- dsa-23au/java-dsa/.gitpod.Dockerfile
- dsa-23au/java-dsa/.gitpod.yml
- new-24wi/SoftwareSetupNEW.md
This is the branch to start developing Winter quarter curriculum, including topic lists, generating the syllabus, etc.
Started a software setup doc about how to sign up for Frontend Masters with GitHub student benefits, to start evaluating it.
The DSAformat got committed to this branch by mistake.
> Begin planning for Winter 2024 (NEW = Networking and Engineering for the Web)

- dsa-23au/java-dsa/weiss-pham-dmv/src/main/resources/learner-long-life.md
> Update learner-long-life.md -mermaid

- dsa-23au/java-dsa/jpract-app/pom.xml
- dsa-23au/java-dsa/jpract-app/src/main/java/com/BST.java
- dsa-23au/java-dsa/jpract-app/src/main/java/com/practice/app/App.java
- dsa-23au/java-dsa/jpract-app/src/main/java/com/practice/app/mergeSort.java
- dsa-23au/java-dsa/jpract-app/src/test/java/com/practice/app/AppTest.java
- dsa-23au/java-dsa/jpract-app/src/test/java/com/practice/app/mergeTest.java
Just created a new merge sort from scratch that works in a new maven project I made for practicing because I got confused about everything.
> MergeSort!

- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/NearestNeighbor.java
- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/Point.java
- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/PointD.java
Needs ints converted to longs to fix overflow errors, but it cycles thru everything in 5 seconds.
> NearestNeighbor Foundations

- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/BallNode.java
- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/BallTree.java
- dsa-23au/java-dsa/sorting/src/test/java/dev/codewithfriends/NearestNeighborTest.java
> First attempt at BallTree nearest neighbor search

- dsa-23au/java-dsa/weiss-pham-dmv/src/main/resources/ndeanon25.md
- I made a very simple DMV
- Only walk in, no appointments
- DMV only helps with Vehicle Registration and Driver Licenses
> Create ndeanon25.md for Assignment 5 DMV mermaid diagram

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/EvilHangman.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/Fib.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/HangmanManager.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/Lottery.java
> Ndeanon25-update

- dsa-23au/java-dsa/Torsten/src/main/java/com/ActivityTor/app/AppleWatchDataApp.java
- dsa-23au/java-dsa/Torsten/src/main/java/com/ActivityTor/app/DataStorage.java
> Added Methods and Print Methods to Data Storage

- dsa-23au/java-dsa/jon-app/jon-app/src/main/java/com/jon/app/CrimeDatabase.java
Gonna ask for help on what data structure would be best for large data sets. Array List? Hash maps?
> added addCrimeData function

- dsa-23au/java-dsa/jon-app/jon-app/src/main/java/com/jon/app/CrimeDatabase.java
Used a hashmap since it will be easier to access the database because each there is data that are Strings, Integers, and Floats
> added addCrimeData method

- dsa-23au/java-dsa/NMac-app/src/main/40CodingInterviewQuestions.md
40  coding interview questions from the MHL hack week.
> 40 Coding interview question

- dsa-23au/java-dsa/NMac-app/src/Driving_Analysis.java
// The purpose of this program:
// Using the CSV file
// Calculate the total elapsed time driving divided by the total distance
// Print out the table
// So far the program does not read the csv file correctly.
// The program is reading driver although set to read the distance
// Not sure if the elapsed time being double minutes will conflict with it assumes to be in hours
> Driving Analysis program

- dsa-23au/java-dsa/pswish-natmcl/LatestVersion/TestDriverToDriveData.py
I created a test case for the python DriverToDriveData called TestDriverToDriveData. 
I am not entirely sure how the test functions operate and I am not understanding how to resolve the error. 
I tried a couple solutions but no good so far. I believe it is saying the error is with the imports. I am uncertain how to resolve it.
the error is:
"[ERROR]
Traceback (most recent call last):
Failure: builtins.tuple: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'DriverToDriveData.DriverToDriveData'; 'DriverToDriveData' is not a package"), <traceback object at 0x0000019105810300>)
"
> Unit Test 

- dsa-23au/java-dsa/NMac-app/src/MissingNumberFinder.java
> Missing Number Finder

- dsa-23au/java-dsa/datasets/NathanMcL_Time_Driving_Spreadsheet_test7.txt
Data submission into the datasets directory.
> Time Driving Data

- dsa-23au/java-dsa/dynamic-programming/src/main/java/dev/codewithfriends/App.java
Work in progress Make change java program
> Make change program

- dsa-23au/java-dsa/NMac-app/src/Dining_Philosophers.java
Chapter 15: Threads and Locks
pg. 174-179
Problems: 15.3 Dining Philosopher
For help pg. 449
This was fun. More comments need to be added to describe what the code is doing. 
The term "reentrant" means that the lock can be acquired multiple times by the same thread. 
There are issues with this code. starters it should be OOP and it is not.
> Dining Philosopher pseudocode 

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/ImpossibleHangman.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/leftRotate.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/quickSorter.java
- dsa-23au/ndeanon25/src/test/java/com/ndeanon25/HangManTest.java
> changes in my folder

- dsa-23au/java-dsa/NMac-app/src/PseudoSherlockandArray.md
- dsa-23au/java-dsa/NMac-app/src/SherlockandArray.java
Monday morning,
See the Sherlock and Array pseudocode before reviewing the code.
> Sherlock and Array, and pseudocode

- dsa-23au/java-dsa/Torsten/src/main/java/SherlockandArray.java
my pseudpcode for this problem: https://www.hackerrank.com/challenges/sherlock-and-array/problem
> Tor HackerRank Problem pseudocode

- dsa-23au/java-dsa/NMac-app/src/PythonLoops2.py
This program is from @wagorndyl pseudocode submission to: https://www.hackerrank.com/challenges/java-loops/problem.
> PythonLoops2

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/Graph.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/PrimsMST.java
- dsa-23au/ndeanon25/src/test/java/com/ndeanon25/PrimsMSTtest.java
> Worked on the MST

- dsa-23au/java-dsa/mstbydyl/pom.xml
- dsa-23au/java-dsa/mstbydyl/src/main/java/com/mycompany/app/App.java
- dsa-23au/java-dsa/mstbydyl/src/test/java/com/mycompany/app/AppTest.java
just a few lines I'm not certain about
> Dylana's Prim's

- dsa-23au/java-dsa/pswish-pipeline/Hackerrank_problems/LeftAndRight.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/Average.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/BackupLogic.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/DriverConfig.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/DriverData2.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/DriverMain.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/DriverModes.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/tests/test_DriverConfig.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/tests/test_DriverData.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverFiles/tests/test_DriverMain.py
- dsa-23au/java-dsa/pswish-pipeline/python/Version1_3/DriverResources/changelog.md
- dsa-23au/scripts/build-all.sh
> updating the config to search for the latest config
> Pytest was having a hard time resolving inputs
Changed some tests and some logic
Added a function to search for newest csv
> Need to test on main project branch to see if everything still works
> Pytest showing 100 and 66% coverage, need to add more
Related design document link: pending
> Pswish pipeline

- dsa-23au/java-dsa/NMac-app/src/PseudoCodeSherlockArray.md
This pseudocode is from the Hackerrank challenge Sherlock and Array.
> PseudocodeSherlockArray

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/leftRotate.java
Changed the left rotate to right rotate
> Update leftRotate.java for Tuesday

- dsa-23au/java-dsa/NMac-app/src/LeftRotate.java
- dsa-23au/java-dsa/NMac-app/src/LeftRotate.md
LeftRotate Nathan and Nathan team build.
> LeftRotate Tuesday team build

- dsa-23au/java-dsa/MarmotBathTime/src/problems/problems.java
- dsa-23au/java-dsa/NMac-app/src/LeftRotate.java
- dsa-23au/java-dsa/NMac-app/src/LeftRotate.md
- dsa-23au/java-dsa/NMac-app/src/PseudoCodeSherlockArray.md
- dsa-23au/java-dsa/jon-app/src/main/java/com/jon/app/Graph.java
- dsa-23au/java-dsa/jon-app/src/main/java/com/jon/app/PrimsMST.java
- dsa-23au/java-dsa/jon-app/src/test/java/com/jon/app/AppTest.java
- dsa-23au/java-dsa/jon-app/src/test/java/com/jon/app/PrimMSTtest.java
- dsa-23au/java-dsa/jonah-app/CatAndMouse.java
- dsa-23au/java-dsa/jonah-prim/prim/src/main/java/com/jonaheadie/Edge.java
- dsa-23au/java-dsa/jonah-prim/prim/src/main/java/com/jonaheadie/Node.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/leftRotate.java
Pseudo code about a previous problem
> Duc's Pseudocode

- dsa-23au/java-dsa/Duc_assignment/Pseudocode
Adding pseudocode from an earlier Hackerrank example
> Adding Duc's Pseudocode

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/ImpossibleHangman.java
> Updates on my final project

- dsa-23au/java-dsa/NMac-app/src/test/java/com/nathanMcL/app/total_miles.py
This program is for Driver modes python unit test.
> Unit test for Distance

- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/AppleWatchDataApp.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/BST.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/BSTNode.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/DataStorage.java
> worked on project with Quinn and have some changes

- dsa-23au/notes/docs/week-09/Co-Creation-09.md
My week 9 Co-Creation sentences.
> Co-Creation week9

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/AnagramSorter.java
> AnagramSorter for HW5

- dsa-23au/java-dsa/jon-app/src/main/java/com/jon/app/CrimeData.java
- dsa-23au/java-dsa/jon-app/src/main/java/com/jon/app/CrimeDatabase.java
Added a simple class that represents a data structure for storing info for the crime record as well as other new methods I will have to work on
> Jon-projectupdate

- dsa-23au/java-dsa/NMac-app/src/OpenClosedSource.md
My comments regarding the open source vs closed source topics.
> OpenClosedSource

- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/Graph.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/GraphMatrix.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/GraphSparse.java
- dsa-23au/ndeanon25/src/main/java/com/ndeanon25/PrimsMST.java
Worked in class, does not run, but understands what we want to do, just syntax stuff.
> Worked on te Prim's Algorithm

- dsa-23au/java-dsa/NMac-app/src/test/PrimsMethod/Graph.java
- dsa-23au/java-dsa/NMac-app/src/test/PrimsMethod/MST_Graph.java
Prim's method and Minimum Spanning Tree possible implementation.
> Prims Method and MST

- .github/workflows/maven.yml
Fix continuous integration with Java project builds with maven.
> Update maven.yml to remove update-deps

- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/AppleWatchDataApp.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/DataStorage.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/Runtime.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/SoundLevelsDataPoint.java
> Dav tor Average Step Count

- dsa-23au/java-dsa/Torsten-David.app/README.md
- dsa-23au/java-dsa/Torsten-David.app/src/test/java/com/ActivityTor/app/DataStorageTest.java
> added JunitTest Method

- dsa-23au/java-dsa/Torsten-David.app/README.md
> added READ ME FILE

- dsa-23au/java-dsa/NMac-app/src/DriverToDrive/driverToDriveData/DataSet_DSAau_pswish_test1.csv
- dsa-23au/java-dsa/NMac-app/src/DriverToDrive/driverToDriveData/DriverToDriveData.java
- dsa-23au/java-dsa/NMac-app/src/DriverToDrive/driverToDriveData/DriverToDriveData_Pseudocode.md
- dsa-23au/java-dsa/NMac-app/src/DriverToDrive/driverToDriveData/Time_Driving_Spreadsheet_test5.csv
This program is a Java version of the Driver to Drive Python program created by pswish. This Java version still needs attention.
There is pseudocode based on the Python version that has been used in trying to recreate the program in Java.
> Java version of Driver to Drive

- dsa-23au/java-dsa/NMac-app/src/DriverToDriveData_Python/DataSet_DSAau_pswish_test2.csv
- dsa-23au/java-dsa/NMac-app/src/DriverToDriveData_Python/DriverConfig.py
- dsa-23au/java-dsa/NMac-app/src/DriverToDriveData_Python/DriverToDriveData.py
- dsa-23au/java-dsa/NMac-app/src/DriverToDriveData_Python/TestDriverToDriveData.py
- dsa-23au/java-dsa/NMac-app/src/DriverToDriveData_Python/TestTotalMiles.py
- dsa-23au/java-dsa/NMac-app/src/DriverToDriveData_Python/Time_Driving_Spreadsheet_test7.csv
My Test version of the Driver to drive data program
> Python test version

- dsa-23au/java-dsa/faulkdf-app/README.md
Realistically this could be better. I am also not quite done adding to my final project.
> Updated ReadMe.md

- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Main_SignalStrength/SignalStrength.py
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Main_SignalStrength/SignalStrengthConfig.py
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/SignalStrengthResources/wifi_signal_strength.csv
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Test_SignalStrength/SignalStrengthConfig_Test.py
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Test_SignalStrength/SignalStrength_Test.py
These files are to process a wifi's signal strength via CSV data.
> Signal Strength build

- dsa-23au/java-dsa/Torsten-David.app/README.md
- dsa-23au/java-dsa/Torsten-David.app/src/test/java/com/ActivityTor/app/DataStorageTest.java
> new REadme

- dsa-23au/java-dsa/Torsten-David.app/README.md
> added to ReadME file

- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Main_SignalStrength/SignalStrength.py
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Main_SignalStrength/SignalStrengthConfig.py
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Test_SignalStrength/SignalStrengthConfig_Test.py
- dsa-23au/java-dsa/NMac-app/src/SignalStrength/Test_SignalStrength/SignalStrength_Test.py
These updates are for the SignalStrength.py application. I updated the menu options to correctly read the CSV file. 
@pswish If you look at the code you will see how I adapted your original drivertodrive menu code into this program.
I still have to implement an algorithm that will have to sort and do something... Then print the data the way I want it to be printed.
> Updated source code

- dsa-23au/java-dsa/ndeanon25/README.md
- dsa-23au/java-dsa/ndeanon25/src/main/java/com/ndeanon25/FinalProjectDSA/HangmanLogic.java
- dsa-23au/java-dsa/ndeanon25/src/main/java/com/ndeanon25/HWProjects/Quiz.java
- dsa-23au/java-dsa/ndeanon25/src/test/java/com/ndeanon25/HangManTest.java
-Worked on README
-Updated junit tests
> final project

- dsa-23au/java-dsa/ndeanon25/README.md
- dsa-23au/java-dsa/ndeanon25/src/main/java/com/ndeanon25/FinalProjectDSA/HangmanLogic.java
- dsa-23au/java-dsa/ndeanon25/src/main/java/com/ndeanon25/FinalProjectDSA/ImpossibleHangman.java
> ReadMeFile updates!!

- dsa-23au/Jon-AppFinal/README.md
- dsa-23au/Jon-AppFinal/crime_project/Mermaid.md
- dsa-23au/Jon-AppFinal/crime_project/crime_database/crime_database.py
- dsa-23au/Jon-AppFinal/crime_project/main.py
I want suggestions on more data structures I could use to manipulate the data more.
> Final Touches Before prez

- dsa-23au/java-dsa/Trinity-app/src/main/java/dev/Hiraeth_awaits/Tarot.py
My final code for my final project
> My final project

- dsa-23au/java-dsa/faulkdfdawsonwhi-app/README.md
Did not add the video because it is too large. Video will be submitteed on canvas.
> Updated README

- dsa-23au/java-dsa/faulkdfdawsonwhi-app/README.md
Added the unlisted YouTube [link](https://youtu.be/tIQU3vuzreA) for the project demo.
> modified readme with link to demo video

- dsa-23au/docs/week-02/Co-Creation-02.md
Here's a resubmission of my week to call creation I submitted it on the wrong portion I was using canvas instead of GitHub
> DavDunston updated Co-Creation for2.md

- dsa-23au/docs/week-04/Assignment-04.md
Here is my week four assignment and update you my co-creation for this week
> Dav Dunstpn Update Assignment-04.md

- dsa-23au/docs/week-09/Co-Creation-09.md
Who is my week Aiko creation in assignment I wanted to definitely take my time with us so here it is finally
I'm super grateful for everyone's responses and cooperation up to this point I want to work more with you in the future go Evergreen !
> DavDun Update Co-Creation-09.md

- dsa-23au/java-dsa/Torsten-David.app/README.md
How did some much-needed spell corrections and a plug-in list to our READ ME
> Dav Dun Update README.md

- dsa-23au/java-dsa/arrays-links/src/main/java/dev/codewithfriends/Stack.java
Worked on the Stack class and finished it to run. 
-Added Peek
-Updated Pop and push
- Added size
> Updated Stack to run HW7

- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/AppleWatchDataApp.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/Runtime.java
What I have right now does not work. I tried chat GPT, it's saying something about the file path
> added append method to add more csv data

- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/AppleWatchDataApp.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/DataStorage.java
- dsa-23au/java-dsa/Torsten-David.app/src/main/java/com/ActivityTor/app/Runtime.java
> added new menu options!

- web-24wi/assignments/nathanMcL/READme.md
> Created folder, added readme

- .gitpod.Dockerfile
Responding to issue #625 
Still needs NodeJS
> Added rust toolchain install, netcat, tcpdump, telnet, and net-tools

- web-24wi/assignments/poperigby/infra/.bash_history
> Commit .bash_history

- web-24wi/assignments/Zachsrob/upper-division-cs/web-24wi/assignments/Zachsrob/infra/history.txt
added History.txt from powershell.
> added Zach's history.txt

- web-24wi/assignments/faulkdf/frontend/week1/index.html
Had errors in formatting. Fixing so it looks better
> Update index.html (fixed errors)

- dsa-23au/java-dsa/pixel-sort/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
> RGeiser Week 01 Pull Request

- web-24wi/assignments/emoleary/frontend/week2/index.js
- web-24wi/assignments/emoleary/infra/thurs_jan11_history.txt
- Included a copy of my command history, and a webpage stub.
- Begun to outline Web Frontend Week 1 project
- Created structure for week2, to practice making a pull request from the command line.
- PR Request
> "PR Request"

- dsa-23au/java-dsa/pixel-sort/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
- web-24wi/assignments/ndeanon25/frontend/week1/index.html
- web-24wi/assignments/ndeanon25/frontend/week1/touchIndex.html
> Update to my index.html

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Coffee_app/templates/index.html
> Updated the index instructions

- web-24wi/assignments/EvergreenTor/Frontend/about.html
- web-24wi/assignments/EvergreenTor/Frontend/index.html
> addded about.html and some starting code

- web-24wi/assignments/nathanMcL/bash_history.md
> bash history

- .vscode/launch.json
- dsa-23au/docs/week-02/Co-Creation-02.md
- dsa-23au/java-dsa/harlee-app/src/jesseAndCookies.java
- dsa-23au/java-dsa/heaps-trees/src/main/java/dev/codewithfriends/BSTMain.java
- dsa-23au/java-dsa/heaps-trees/src/test/java/dev/codewithfriends/BinarySearchTreeTest.java
- dsa-23au/java-dsa/sorting/src/main/java/dev/codewithfriends/App.java
- web-24wi/assignments/harleehair/frontend/week1/index.html
> Harleetemp3

- web-24wi/assignments/ndeanon25/frontend/week1/CoffeeShop/CoffeeShop.html
- web-24wi/assignments/ndeanon25/frontend/week1/CoffeeShop/style.css
-Coffee Shop Website looks good
> Finished FrontEnd HW01

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week2/Calculator_app/READme.md
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week2/Calculator_app/calculator.css
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week2/Calculator_app/calculator.html
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week2/Calculator_app/calculator.js
Created the week 2 folder within my Student Originated Software directory. Within the week 2 folder is my Calculator_app.
> week2 Calculator_app

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/TCP_Server.py
This is from Networking Homework week 2.
> TCP_Server

- web-24wi/assignments/ndeanon25/infra/history.txt
added my command history
added it for my full credits on the Web Infra HW 01
> added history.txt

- web-24wi/docs/AWS-EC2-Setup.md
- web-24wi/docs/week-03/2024-01-25.md
- web-24wi/docs/week-03/Infra-Homework-03.md
- web-24wi/docs/week-04/Infra-Homework-04.md
Infra HW 3 and 4, to start with.
> Week 3 notes and homework, work-in-progress

- web-24wi/projects/pswish/word_master/index.html
- web-24wi/projects/pswish/word_master/style.css
- web-24wi/projects/pswish/word_master/word.js
Worked on this ahead of Thursday's class, almost  a functioning game.
> Adding some code for the word game

- web-24wi/projects/AppleWatchHeathData/api-server/.env
- web-24wi/projects/AppleWatchHeathData/api-server/package-lock.json
- web-24wi/projects/AppleWatchHeathData/api-server/package.json
- web-24wi/projects/AppleWatchHeathData/api-server/schema.prisma
- web-24wi/projects/AppleWatchHeathData/frontend-server/index.html
Paul and I got a start on setting up my final project.
> Torsten's apple watch project start!

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week3/READme.md
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week3/WordMasters/WordMasters.css
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week3/WordMasters/WordMasters.html
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week3/WordMasters/WordMasters.js
work in progress.
loads
Player can input & remove letters
If the word is wrong, state changes (orange if close, red incorrect...)
working on the state change for if the word is correct.
inputed  the daily word, but no state change
> week3 wordmasters

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/Clients/TCP_Client.py
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/Clients/UDP_Client.py
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/TCPServer_Book.py
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/TCP_Server.py
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/UDP_Server.py
I like typing... :) These are TCP and UDP servers and clients I have been testing. 
@anyone_reading_this, does it matter which port you choose while testing out the server and client connection? I understand the lower ports are for common services that you probably don't want to connect to. 
Well-known ports (0-1023): These ports are reserved for specific services, such as HTTP (port 80) and FTP (port 21).
Registered ports (1024-49151): These ports are assigned to specific applications by the Internet Assigned Numbers Authority (IANA).
Dynamic or private ports (49152-65535): These ports are used by applications for temporary connections. Non-privileged ports are indeed ports above 1023.
>  Servers and Clients

- web-24wi/assignments/faulkdf/frontend/week4/wordGuess/index.html
- web-24wi/assignments/faulkdf/frontend/week4/wordGuess/style.css
- web-24wi/assignments/faulkdf/frontend/week4/wordGuess/word.js
borrowed some framework from @pswish (thank you :) )
> Added WIP for word game

- web-24wi/assignments/AkinaSS/infra/week3/package.json
- web-24wi/assignments/AkinaSS/infra/week3/pnpm-lock.yaml
- web-24wi/assignments/AkinaSS/infra/week3/server.js
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/.gitignore
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/package-lock.json
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/package.json
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/prisma/schema.prisma
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/tsaconfigure.json
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/tsconfig.json
Updating week4 hw for the current being, still stuck at how to do migration, create database and systemd unit
> Update week4 infra hw

- web-24wi/assignments/Ryan-Geiser/frontend/week2/Calculator/index.html
- web-24wi/assignments/Ryan-Geiser/frontend/week2/Calculator/index.js
- web-24wi/assignments/Ryan-Geiser/frontend/week2/Calculator/styles.css
just adding my html, js, and css files for the calculator
> creating the calculator for front end HW 2

- web-24wi/assignments/rain/infra/week4/pages/index.html
- web-24wi/assignments/rain/infra/week4/pages/login.html
- web-24wi/assignments/rain/infra/week4/server.js
updating server.js to process post request from login form
> server.js handling post request

- web-24wi/assignments/faulkdf/frontend/week3/api-server/server.js
- web-24wi/assignments/faulkdf/frontend/week4/login-project/README.md
added the post clause in server.js and a readme file with my codependent. I'll split everything up into real files as soon as I get a chance.
> added things from in class

- web-24wi/assignments/ndeanon25/frontend/week2/index.html
- web-24wi/assignments/ndeanon25/frontend/week2/script.js
- web-24wi/assignments/ndeanon25/frontend/week2/styles.css
> added calc hw2

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/index.html
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/script.js
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/style.css
This is my wireframe Implementation. It does not have  like a main landing page. I have been working on the buttons and just finished the JS error handling. The next step is to link my python data to this. Ideas on how to improve this are welcome.
> raspberry health

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/about.html
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/landing.html
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/privacy.html
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/style.css
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/terms.html
Created a landing page, within the landing page are the about page, privacy page and terms of service page. The landing page has a link to my main menu page.
> created landing page

- web-24wi/projects/pswish/api-server/package.json
- web-24wi/projects/pswish/api-server/pnpm-lock.yaml
- web-24wi/projects/pswish/api-server/server.js
- web-24wi/projects/pswish/api-server/src/server.ts
Functioning API server up to end of class Monday, Feb 05.
> Adding working user code from class today

- web-24wi/assignments/ndeanon25/frontend/week5/README.md
- web-24wi/assignments/ndeanon25/frontend/week5/index.html
made dir and did html and questions
> inclass frontend5

- web-24wi/assignments/faulkdf/week5/flowchart?/README.md
- web-24wi/assignments/faulkdf/week5/flowchart?/index.html
@faulkdf and @tw-edu worked on this together
Mermaid is easier than I remember :)
> Added readme and index.html from in class assignment 

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week5/HTML_CSS_review_questions.md
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week5/simpleStaticPage.html
> in-class activites

- web-24wi/assignments/wshine/frontend/week5/arr.yale.edu-schema
2/6/2024 second hour class activity
> add yale.edu db schema mockup

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/landing.html
Corrected the linkedin link within the landing page.
>  linkedin link

- web-24wi/projects/pswish/react-admin/README.md
- web-24wi/projects/pswish/react-admin/package-lock.json
- web-24wi/projects/pswish/react-admin/src/App.js
- web-24wi/projects/pswish/react-admin/src/index.js
- web-24wi/projects/pswish/react-admin/src/scenes/dashboard/index.jsx
- web-24wi/projects/pswish/react-admin/src/scenes/global/Sidebar.jsx
- web-24wi/projects/pswish/react-admin/src/scenes/global/Topbar.jsx
- web-24wi/projects/pswish/react-admin/src/theme.js
- Fixed a bug where the light/dark selector was not functioning properly (pallette vs palette typo) 
- Started work on the Sidebar. (On the feature chopping block).
-  Looking good! :
> Updating and adding some react-dashboard work

- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/server.cjs
- web-24wi/assignments/ty_f/week-3/placeholder.js
hotfix since I add stupid things that might not working
> hotfix for server.cjs

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Project/SystemPerformanceLog/RaspberryHealth/landing.html
Trying to sort out why my images are not displaying when I start the webpage through gitpod... 
I am certain my directory path is correct for gitpod.
I checked the file permission of my images within the SystemLogResources directory, they are all set correctly as: -rw-r--r--
When I run my webpage locally throuhg VS code everything displays at is should.
I think that is slightly different than web-based?
> Images still not displaying

- web-24wi/assignments/ppham/infra/api-server/dev.sh
- web-24wi/assignments/ppham/infra/api-server/package.json
- web-24wi/assignments/ppham/infra/api-server/server.js
> Prototype local dev setup scripts

- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/package-lock.json
- web-24wi/assignments/AkinaSS/infra/week4/hello-prisma/package.json
- web-24wi/assignments/AkinaSS/randomShellFiles/ddos-paul.sh
- web-24wi/assignments/AkinaSS/randomShellFiles/milhouse.sh
- web-24wi/projects/Duck/api-server-start.sh
- web-24wi/projects/Duck/package-lock.json
- web-24wi/projects/Duck/package.json
Adding/copying what we did to the projects folder in the class 
Also, this is a greeting from a new instance, welcome back I guess
> Update projects file

- web-24wi/scripts/easy-tunnel/easy-tunnel.sh
- web-24wi/scripts/easy-tunnel/readme.md
Added a script for a persistent tunnel to your remote server's postgresql port and appropriate readme file
> easy-tunnel script

- web-24wi/projects/ProjectRaspberry/SystemPerformanceLog/SystemLogResources/SystemLog.sh
The comment for CPU Usage was vauge, and I also forgot what the script did so I improved the comment
> updaeted CPU Usage comment

- web-24wi/assignments/ndeanon25/frontend/week3/index.html
- web-24wi/assignments/ndeanon25/frontend/week3/script.js
- web-24wi/assignments/ndeanon25/frontend/week3/styles.css
> Changes in ndeanon25 assignments

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/Clients/TCPclient_Logs.py
- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/Servers/TCPserver_Logs.py
Neworking Week 6
TCP server and client.
The purpose was to observe what happens when a message is dropped by the server through WireShark.
This TCP server logs the connection of the client once they connect to the server.
The server logs the date, time, Ip address, and Port of the client.
The client is prompted to enter a sentence.
If entered properly, the server will return the sentence in all capital letters.
If the server is unable to process the sentence or the message is dropped,
A message will print in the server's terminal.
> Networking TCP server/client programs

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week7/READme.md
week 7 directory and READme file created
> week7 directory and readme

- web-24wi/projects/pswish/prod/driver_flask/app.py
Oops, well not a huge secret yet
> Moving hardcoded creds to a config file and then gitignoring the config file

- web-24wi/assignments/faulkdf/frontend/week7/README.md
- web-24wi/projects/faulkdf-dawsonwhi/pages/graph.html
- web-24wi/projects/faulkdf-dawsonwhi/server.js
added mermaid graph from in class
> Ic 20 feb faulkdf

- web-24wi/projects/faulkdf-dawsonwhi/pages/graph.html
- web-24wi/projects/faulkdf-dawsonwhi/server.js
still cant get the graph to display but at least these problems are fixed
> fixed a couple of typos and changed port to 5001

- web-24wi/assignments/faulkdf/frontend/week7/README.md
> continued modifying readme in week7 folder

- web-24wi/assignments/nathanMcL/StudentOriginatedSoftware/week7/UntedStatesMap.html
> USA map instructions

- web-24wi/projects/pswish/.gitignore
- web-24wi/projects/pswish/prod/driver_flask/app.py
- web-24wi/projects/pswish/prod/driver_flask/database.py
- web-24wi/projects/pswish/prod/react-prod/src/scenes/dashboard/index.jsx
- web-24wi/projects/pswish/prod/react-prod/src/scenes/form/index.jsx
- web-24wi/projects/pswish/restart-flask.sh
Continued work on Benchmark 3
1. Started with dashboard form outputting only to DOM console(end of the tutorial). 
2. Added a React method to pass the form to the Flask server
3. Modified mydb with SQLAlchemy and added a user table and schema
4. Added a method to handle the form from the dashboard and send it to the database and then return a success alert to the dashboard interface for user.
5. Resuts in the db:
End of benchmark 3
> Adding functionality to create user by user form on dashboard - End of Benchmark 03

- web-24wi/projects/ProjectRaspberry/SystemPerformanceLog/Server/READme.md
adding a readme to the project directory version of my RaspberryHealth project's server directory.  The read me will have images of what my pages look like as of 2/24/24.
> readme for the MacNserver

- web-24wi/projects/pswish/restart-flask.sh
- web-24wi/scripts/create_branch_and_push.sh
1. The restart-flask script is for my flask server: Stops the current service,  asks me restart the service, opens an interactive terminal or quits leaving the service stopped. I assigned this to an alias in my .zshrc
2. The create-branch-and-push script asks the user for a new branch name creates that branch, then asks the user if they are ready to push and if not, prints out git status. I also assigned this to an alias.
> Starting Benchmark04: Adding some helper scripts

- web-24wi/projects/Hostile/finalproject/client/src/components/window.tsx
- web-24wi/projects/Hostile/finalproject/client/src/main.tsx
- web-24wi/projects/Hostile/finalproject/devNotes.txt
> add devNotes.txt

- web-24wi/assignments/wshine/week10/exercises/05_higher_order/code/chapter/05_higher_order.js
- web-24wi/assignments/wshine/week10/exercises/05_higher_order/code/intro.js
- web-24wi/assignments/wshine/week10/exercises/05_higher_order/code/load.js
- web-24wi/assignments/wshine/week10/exercises/05_higher_order/code/scripts.js
- web-24wi/assignments/wshine/week10/exercises/05_higher_order/index.html
- web-24wi/assignments/wshine/week10/exercises/05_higher_order/run_with_node.js
- web-24wi/assignments/wshine/week10/exercises/beancounting.ts
- web-24wi/assignments/wshine/week10/exercises/chessboard.ts
- web-24wi/assignments/wshine/week10/exercises/deep-comp.ts
- web-24wi/assignments/wshine/week10/exercises/fizzbuzz.ts
- web-24wi/assignments/wshine/week10/exercises/higher-order-functions.ts
- web-24wi/assignments/wshine/week10/exercises/lists.ts
- web-24wi/assignments/wshine/week10/exercises/loop-triangle.ts
- web-24wi/assignments/wshine/week10/exercises/minimum.ts
- web-24wi/assignments/wshine/week10/exercises/recursion.ts
- web-24wi/assignments/wshine/week10/exercises/reverse-array.ts
- web-24wi/assignments/wshine/week10/exercises/sum-of-range.ts
- web-24wi/assignments/wshine/week10/package-lock.json
- web-24wi/assignments/wshine/week10/package.json
- web-24wi/assignments/wshine/week10/tsconfig.json
eloquent js exercises done up through chapter 5
> Wshine week10

- web-24wi/assignments/ndeanon25/infra/api-design/README.md
> Ndeanon25 readme sos

- ai-24sp/prototypes/prototype-08/README.md
I created a read-me file so we can start considering the prompts I have on the document, as we develop this Ai creation. We can always alter the prompts or add another section if we have to. but it should get us started.
> created read me file

- sc-24sp/prototypes/prototype-10/Cargo.toml
- sc-24sp/prototypes/prototype-10/README.md
- sc-24sp/prototypes/prototype-10/src/lib.rs
- sc-24sp/prototypes/prototype-10/src/main.rs
- sc-24sp/prototypes/prototype-10/src/moves/mod.rs
- sc-24sp/prototypes/prototype-10/src/types/board.rs
- sc-24sp/prototypes/prototype-10/src/types/mod.rs
- sc-24sp/prototypes/prototype-10/src/validators/mod.rs
Worked with @nathanmcl, and typed out main + other files
See changes for details.
> Started Prototype-10 Tic-Tac-Toe Solver

- sc-24sp/OS_code/Makefile
- sc-24sp/OS_code/q1.c
- sc-24sp/OS_code/q2.c
- sc-24sp/OS_code/q3.c
- sc-24sp/prototypes/prototype-09/Cargo.toml
- sc-24sp/prototypes/prototype-09/src/main.rs
- sc-24sp/prototypes/prototype-09/src/moves/mod.rs
- sc-24sp/prototypes/prototype-09/src/types/board.rs
Some of the code completed for prototype-09
> Adding in code for prototype-09

- ai-24sp/prototypes/prototype-07/README.md
see title. 
readme.md wasnt selected in the earlier commit and push
> Forgot to stage the readme file from earlier. File added now

- sc-24sp/prototypes/prototype-10/README.md
- sc-24sp/prototypes/prototype-10/src/types/board.rs
- sc-24sp/prototypes/prototype-10/src/types/mod.rs
- sc-24sp/prototypes/prototype-10/src/validators/mod.rs
added missing code to prototype-10.
See readme for details
> added missing code

- sc-24sp/prototypes/prototype-10/README.md
one more readme update from prototype 10
> updated readme again

- sc-24sp/prototypes/prototype-10/src/moves/mod.rs
- sc-24sp/prototypes/prototype-10/src/moves/ranker.rs
- sc-24sp/prototypes/prototype-10/src/validators/winning.rs
my Question to AI to get the rest of the ranker.rs instructions: "using this rust ranker.rs code:... can you help us figure out: Return all moves that are equally likely to lead to a draw or for next player to win how we can give all moves that help either player win, how to choose moves to return?"
> prototype-10 ranker

- ai-24sp/assignments/NathanMc/READme.md
Created my directory & readme/ Ai-journal for the AI assignments directory.
> created directory & readme

- ai-24sp/prototypes/prototype-08/load_mnist.py
- ai-24sp/prototypes/prototype-08/network.py
- ai-24sp/prototypes/prototype-08/requirements.txt
resolved errors and was able to generate epoch 0.
> updating network & load_mnist code

- ai-24sp/prototypes/prototype-08/.gitignore
- ai-24sp/prototypes/prototype-08/loader.py
- ai-24sp/prototypes/prototype-08/network.py
- ai-24sp/prototypes/prototype-08/run_model.py
- ai-24sp/prototypes/prototype-08/train.py
updated 04/19/2024:
network.py 
added:
loader.py, run_model.py, & train.py ...
> updated network, added: loader.py, run_model.py, & train.py

- ai-24sp/prototypes/prototype-08/network.py
- ai-24sp/prototypes/prototype-08/requirements.txt
updated network.py ,loader.py ,& train.py from working local machine prototype.
> Updated prototype-08

- sc-24sp/assignments/JonahEadieEvergreen/city-addresses/src/city_drawer.rs
- sc-24sp/assignments/JonahEadieEvergreen/city-addresses/src/main.rs
Can be placed anywhere not occupied by a road. This may not be ideal. With a few changes, addresses could be limited to being adjacent to roads, and could occupy more than a single tile.
> Implemented basic addresses

- sc-24sp/assignments/NathanMcL/city-addresses/src/city_drawer.rs
- sc-24sp/assignments/NathanMcL/city-addresses/src/main.rs
Hello, city!
Added avenue 3
Added avenue 4
Added avenue 10
Added avenue 15
Added avenue 18
Added avenue 23
Added avenue 25
Added avenue 34
Added avenue 37
Added avenue 44
Added street 9
Added street 17
Added street 26
Added street 27
Added street 29
Added street 29
Added street 36
Added street 36
Added street 42
Added street 49
Random Avenues: [Avenue { x: 3 }, Avenue { x: 40 }, Avenue { x: 46 }, Avenue { x: 12 }, Avenue { x: 2 }, Avenue { x: 11 }, Avenue { x: 21 }, Avenue { x: 48 }, Avenue { x: 40 }, Avenue { x: 8 }]
Random Streets: [Street { y: 44 }, Street { y: 21 }, Street { y: 27 }, Street { y: 27 }, Street { y: 2 }, Street { y: 1 }, Street { y: 29 }, Street { y: 20 }, Street { y: 4 }, Street { y: 38 }]
...##.....#....#..#....#.#........#..#......#..... …
> updates to city-addresses

- ai-24sp/prototypes/prototype-08/README.md
- ai-24sp/prototypes/prototype-08/network.py
- ai-24sp/prototypes/prototype-08/train.py
Implemented a  dropout function & a Evaluate the Accuracy of the total data trained.
see prototype-08 readme 04/25/2024
> updated trainer: dropout & Evaluate Accuracy

- .gitmodules
Update .gitmodules based on the following fix I found:
https://stackoverflow.com/questions/3240881/git-can-i-suppress-listing-of-modified-content-dirty-submodule-entries-in-sta
> Update .gitmodules with ignore method

- ai-24sp/assignments/AkinaS/.gitignore
- ai-24sp/assignments/AkinaS/data/data.sh
- ai-24sp/assignments/AkinaS/week5/process.py
- ai-24sp/assignments/AkinaS/week5/token_creation.py
- ai-24sp/assignments/AkinaS/week5/tokenizer.py
Adding code for AI lab 5 until 2.4
> Adding tokenizer code from AI lab 5

- ai-24sp/prototypes/prototype-08/MNIST_training_log.csv
- ai-24sp/prototypes/prototype-08/README.md
- ai-24sp/prototypes/prototype-08/network.py
I update  network.py.
1: Created a 'validation split' within network.py (see the README.md).
2: Created an instance where the time per Epoch is marked and once the program has completed it displays the average time it took for each Epoch to complete.
3: Add the new CSV file with all the headers writing to the file.
> updating network.py & readme.md

- sc-24sp/assignments/AkinaS/week3/src/city_drawer.rs
- sc-24sp/assignments/AkinaS/week3/src/main.rs
Modified the code for lab 6, and concluded this week of drawing cities I guess
Everything recorded in the dev diary will be updated after reformatting the previous assignment
> Modified city_drawer code for today's lab

- sc-24sp/assignments/AkinaS/week3/src/city_drawer.rs
- sc-24sp/assignments/AkinaS/week3/src/lib.rs
Adding TokyoAdresser struct
Adding lib.rs from Paul's code, just in case
> Edit some extra things because I'm bored

- sc-24sp/assignments/faulkdf/wasm-game-of-life/.appveyor.yml
- sc-24sp/assignments/faulkdf/wasm-game-of-life/.github/dependabot.yml
- sc-24sp/assignments/faulkdf/wasm-game-of-life/.gitignore
- sc-24sp/assignments/faulkdf/wasm-game-of-life/.travis.yml
- sc-24sp/assignments/faulkdf/wasm-game-of-life/Cargo.toml
- sc-24sp/assignments/faulkdf/wasm-game-of-life/LICENSE_APACHE
- sc-24sp/assignments/faulkdf/wasm-game-of-life/LICENSE_MIT
- sc-24sp/assignments/faulkdf/wasm-game-of-life/README.md
- sc-24sp/assignments/faulkdf/wasm-game-of-life/src/lib.rs
- sc-24sp/assignments/faulkdf/wasm-game-of-life/src/utils.rs
- sc-24sp/assignments/faulkdf/wasm-game-of-life/tests/web.rs
See end of the readme for the dev diary. Did a lot today, somehow didn't do enough
> Lab7 changes from faulkdf

- .gitpod.Dockerfile
Tested and had node v14 and access to nvm upon opening a workspace.
> Fix nvm installation

- ai-24sp/assignments/NathanMc/Prototype_text/week-07/dataloader.py
- ai-24sp/assignments/NathanMc/Prototype_text/week-07/process.py
updated my week 7 process & dataloader.py code. I have not tried to run the programs in gitpod. The files do compile locally. See ` /Assignments/NathanMcL/Prototype_text/ `
> updated week7 code

- sc-24sp/assignments/faulkdf/wasm-game-of-life/README.md
- sc-24sp/assignments/faulkdf/wasm-game-of-life/src/lib.rs
had to add one extra line in index.js that I missed last week. 
the book *is not clear*
> got the animation to work!

- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/Cargo.toml
- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/src/lib.rs
- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/www-backups/bootstrap.js
- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/www-backups/index.html
- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/www-backups/index.js
- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/www-backups/package.json
- sc-24sp/assignments/pswish-sc/game-of-life3/wasm-game-of-life/www-backups/webpack.config.js
Added the code from the book to the end of 4.4, tested sat.
> Game-Of-life end of 4.4

- ai-24sp/assignments/whereismyprozac/week9/gpt_train.py
- ai-24sp/assignments/whereismyprozac/week9/previous_chapters.py
- ai-24sp/assignments/whereismyprozac/week9/requirements.txt
Traceback (most recent call last):
File "/workspaces/upper-division-cs/ai-24sp/assignments/whereismyprozac/week9/gpt_train.py", line 15, in <module>
from gpt_train import GPT_CONFIG_124M
File "/workspaces/upper-division-cs/ai-24sp/assignments/whereismyprozac/week9/gpt_train.py", line 15, in <module>
from gpt_train import GPT_CONFIG_124M
ImportError: cannot import name 'GPT_CONFIG_124M' from partially initialized module 'gpt_train' (most likely due to a circular import) (/workspaces/upper-division-cs/ai-24sp/assignments/whereismyprozac/week9/gpt_train.py)
> circular import fuckery

- ai-24sp/assignments/NathanMc/Prototype_text/week-09/CausalAttentionClass.py
- ai-24sp/assignments/NathanMc/Prototype_text/week-09/MultiHeadAttention.py
- ai-24sp/assignments/NathanMc/Prototype_text/week-09/SelfAttentionClass.py
- ai-24sp/assignments/NathanMc/Prototype_text/week-09/dataloader.py
- ai-24sp/assignments/NathanMc/Prototype_text/week-09/process.py
> upload week-09

- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/.appveyor.yml
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/.github/dependabot.yml
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/.gitignore
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/.travis.yml
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/Cargo.toml
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/LICENSE_APACHE
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/LICENSE_MIT
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/README.md
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/package-lock.json
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/package.json
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/packages/package.json
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/src/lib.rs
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/src/utils.rs
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/tests/web.rs
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/.bin/create-wasm-app.js
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/.gitignore
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/.travis.yml
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/LICENSE-APACHE
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/LICENSE-MIT
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/README.md
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/bootstrap.js
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/index.html
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/index.js
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/package-lock.json
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/package.json
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/pnpm-lock.yaml
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/style.css
- sc-24sp/assignments/pswish-sc/game-of-life3/dev/game_Backup5/wasm-game-of-life/www/webpack.config.js
Wiki DevDiary: https://github.com/TheEvergreenStateCollege/upper-division-cs/wiki/Week-10:-the-last-Lab
Functioning fps measure, lags big time when inspected so needs to be optimized. Forex, running on my MacBook air crashed multiple apps when inspect + firefox ran, it forced quit at 13BG of application memory used.
dev/version5 is a working prototype.
> Adding up to fps phase 1, game-of-life

- ai-24sp/assignments/NathanMc/Prototype_text/GPT_final/gpt_train.py
fix the gitpod resource paths to my additonal pdfs
> update resource paths

- ai-24sp/assignments/whereismyprozac/week9/gpt.py
- ai-24sp/assignments/whereismyprozac/week9/gpt_train.py
- ai-24sp/assignments/whereismyprozac/week9/previous_chapters.py
argv ['gpt_train.py']
Traceback (most recent call last):
File ".../whereismyprozac/week9/gpt_train.py", line 250, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'model.pth'
> file not found

- ai-24sp/assignments/AkinaS/week10/gpt_train_linux.py
- ai-24sp/assignments/AkinaS/week10/interact_with_gpt.py
- ai-24sp/assignments/AkinaS/week9/interact_with_gpt.py
Update the week 10 code with all full options to run on my PC at home to avoid the SSH server disconnecting the session halfway through the code
> Update code to training at home

- sc-24sp/assignments/Wizard0523/wasm-game-of-life/.appveyor.yml
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/.github/dependabot.yml
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/.gitignore
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/.travis.yml
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/Cargo.toml
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/LICENSE_APACHE
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/LICENSE_MIT
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/README.md
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/src/lib.rs
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/src/utils.rs
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/tests/web.rs
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/.bin/create-wasm-app.js
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/.gitignore
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/.travis.yml
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/LICENSE-APACHE
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/LICENSE-MIT
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/README.md
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/bootstrap.js
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/index.html
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/index.js
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/package-lock.json
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/package.json
- sc-24sp/assignments/Wizard0523/wasm-game-of-life/wwww/webpack.config.js
> Griffin gol

- ai-24sp/assignments/AkinaS/week10/interact_with_gpt.py
- ai-24sp/assignments/AkinaS/week4/.gitignore
- ai-24sp/assignments/AkinaS/week4/README.md
- ai-24sp/assignments/AkinaS/week4/data.sh
- ai-24sp/assignments/AkinaS/week4/finetunning.py
- ai-24sp/assignments/AkinaS/week4/load_labels.py
- ai-24sp/assignments/AkinaS/week4/load_mnist.py
- ai-24sp/assignments/AkinaS/week4/loader.py
- ai-24sp/assignments/AkinaS/week4/mnist_loader.py
- ai-24sp/assignments/AkinaS/week4/network.py
- ai-24sp/assignments/AkinaS/week4/run_model.py
- ai-24sp/assignments/AkinaS/week4/train.py
- ai-24sp/assignments/AkinaS/week7/dataloader.py
- ai-24sp/assignments/AkinaS/week7/process.py
- ai-24sp/assignments/AkinaS/week7/three_five_one.py
- ai-24sp/assignments/AkinaS/week7/three_five_three.py
- ai-24sp/assignments/AkinaS/week7/three_five_two.py
- ai-24sp/assignments/AkinaS/week7/three_four_one.py
- ai-24sp/assignments/AkinaS/week7/three_four_two.py
- ai-24sp/assignments/AkinaS/week7/three_six_one.py
- ai-24sp/assignments/AkinaS/week7/three_six_two.py
- ai-24sp/assignments/AkinaS/week7/three_three_one.py
- ai-24sp/assignments/AkinaS/week7/three_three_two.py
- ai-24sp/assignments/AkinaS/week8/five_four.py
- ai-24sp/assignments/AkinaS/week8/five_one.py
- ai-24sp/assignments/AkinaS/week8/five_three.py
- ai-24sp/assignments/AkinaS/week8/five_two.py
- ai-24sp/assignments/AkinaS/week8/previous_chapters.py
- ai-24sp/assignments/AkinaS/week9/paul_gpt_train.py
* Commit the missing lab code for completionist purposes
* Propose a change to the finetuning code for the gpt_training in week 10, however, I'm still wrapping my head around it with no ends so I decided to post it as it is with some code from loading the weight, I believe this is what we suppose to do but then I don't really know
* I have only made changes so far to the fine-tuning code, not the training one, since the complete code with Paul's modification to keep the model after every training (thank you Paul) is still stuck on his anti-villain GPU server and waiting to be committed and got the model checked out since I don't have any access window 
* At this point it's only for fun and I'm still waiting for the full credits coming but I am interested in how he did the modification and …
> Final ai commit
